### ISSUE TITLE
大兄弟，你滴代码有问题

### ISSUE THREAD

**Issue by yuyeqianxun** [Harrison94pxxxxx/zhihu-daily-vue#1]
我是vue萌新，看到你的项目后，下载下来发现有问题。花了一天时间，参考了别人的项目才把首页搞正常了。处理如下：
Home.vue 
getHomeLists () {
        this.$http.get('_https://zhihu-daily.leanapp.cn/api/v1/last-stories_').then(response => {
          for (let i = 0; i < response.data.STORIES.stories.length; i++) {
            response.data.STORIES.stories[i].images[0] = 'http://read.html5.qq.com/image?src=forum&q=5&r=0&imgflag=7&imageUrl=' + response.data.STORIES.stories[i].images[0]
          }
          this.homeLists = response.data.STORIES.stories
        }, response => {
          console.log('获取数据失败')
        })
      },
斜体部分你之前请求的是before-stories加个当前时间，完全请求不到啊，大概是你没处理时间格式。
watchHeight () {
        var heightCounter = 0
        this.heightCounter1 = 1
        var that = this
        var date = new Date
        setInterval(function () {
          if (window.screen.height + document.body.scrollTop > document.body.clientHeight - 3) {
            that.$store.commit('setShowLoading', 1)
            heightCounter++
            var day=heightCounter-2//我也不知道为什么是-2，我以为是-1，尝试之后发现-2才行
            if (heightCounter > 1 && that.heightCounter1 === 1) {
            	const before = moment(date).subtract(day, 'days').format('YYYYMMDD')
              that.$http.get('_https://zhihu-daily.leanapp.cn/api/v1/before-stories/' + before_).then(response => {......省略
上面的斜体部分，你发出的请求也获取不到，我看别人引入了monent.js这个库来处理时间，所有我也这样做了，const before = moment(date).subtract(day, 'days').format('YYYYMMDD')这一段的意思是date-day获取到的时间，比如现在是20170601，day是0，那before=20170601.api取到的数据就是5月31号的数据。这样滚动出来的数据是和知乎日报的app是一样的。

       我瞎蒙的，有啥问题，请见谅

**Comment by ppppp-x-x** [comment]
非常感谢你发现了这个问题并且还去仔细看了我的代码(代码实在是有点太乱了，非常抱歉)

## 1.关于你提到的请求时所用到当前时间的问题

> 斜体部分你之前请求的是before-stories加个当前时间，完全请求不到啊，大概是你没处理时间格式。
 
这里的当前时间nowData我是在APP.vue里面处理了时间格式的，然后通过Vuex管理，便于重复利用。
<pre>      getMyDate () {
        var myDate = new Date()
        var year = myDate.getFullYear()
        var month = myDate.getMonth() + 1
        if (month < 10) {
          month = '0' + month
        }
        var date = myDate.getDate()
        if (date < 10) {
          date = '0' + date
        }
        this.myDate = year + '/' + month + '/' + date
        var nowDate = year + month + date
        this.$store.commit('setDate', nowDate)
      }
    },</pre>
出现首页无法加载的原因是我忘记处理date了，在日期为一位数时要在日期前加上0。现已修改。


## 2.你所说的应该是首页上拉加载的问题，经过我刚刚测试，上拉加载应该是没有问题的，数据也是正常的。
